name: mmm-residence-chunk-bridge
main: local.mmm.residencechunk.MMMResidenceChunkBridgePlugin
version: 0.24.0
api-version: '1.21'
folia-supported: true
author: Xiaomenxin
depend: [Residence, Vault]
softdepend: [MMMVaultSync]
libraries:
  - com.mysql:mysql-connector-j:9.3.0
commands:
  mmmland:
    description: 区块化领地菜单与管理命令
    usage: /mmmland help
    aliases: [mland]
permissions:
  mmmland.admin:
    default: op
  mmmland.use:
    default: true
